spring:
  datasource:
    url: "jdbc:postgresql://localhost/lightexpenses"
    username: lightexpenses
    password: lightexpenses
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

  freemarker:
    cache: false

  social:
    facebook:
      app-id: 182138022132672
      app-secret: f10746b3436ba2648b5e861aa7906c74


server:
  session:
    persistent: true
    store-dir: ./sessions
    tracking-modes: COOKIE



#security:
#  oauth2:
#    client:
#      clientId: lightexpense
#      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#      accessTokenUri: https://github.com/login/oauth/access_token

endpoints:
  shutdown:
    enabled: true
    sensitive: true

logging:
  level:
    org.springframework.security: debug